
package calculadora;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JFrame;
import javax.swing.UIManager;

public class CalculadoraGuiPanel extends javax.swing.JPanel 
{
    private String input;
    private String output;
    private boolean igual,decimal;
    private BigDecimal total;
    private final static RoundingMode TIPO_DE_REDONDEO=RoundingMode.HALF_EVEN;
    private final static int ESCALA=20;
    
    public CalculadoraGuiPanel() 
    {
        initComponents();
        reiniciarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tecladoPanel = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonBorrarUltimo = new javax.swing.JButton();
        botonPorcentaje = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonDecimal = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        textboxOutput = new javax.swing.JTextField();
        textboxInput = new javax.swing.JTextField();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(240, 310));
        setMinimumSize(new java.awt.Dimension(240, 310));
        setPreferredSize(new java.awt.Dimension(240, 310));
        setLayout(new java.awt.BorderLayout());

        tecladoPanel.setFocusable(false);
        tecladoPanel.setMaximumSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setMinimumSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setPreferredSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setLayout(new java.awt.GridLayout(5, 4));

        botonCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCancelar.setText("C");
        botonCancelar.setFocusable(false);
        botonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCancelar.setMaximumSize(new java.awt.Dimension(50, 50));
        botonCancelar.setMinimumSize(new java.awt.Dimension(50, 50));
        botonCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonCancelar);

        botonBorrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBorrar.setText("CE");
        botonBorrar.setFocusable(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setMaximumSize(new java.awt.Dimension(50, 50));
        botonBorrar.setMinimumSize(new java.awt.Dimension(50, 50));
        botonBorrar.setPreferredSize(new java.awt.Dimension(50, 50));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonBorrar);

        botonBorrarUltimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonBorrarUltimo.setText("<-");
        botonBorrarUltimo.setFocusable(false);
        botonBorrarUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrarUltimo.setMaximumSize(new java.awt.Dimension(50, 50));
        botonBorrarUltimo.setMinimumSize(new java.awt.Dimension(50, 50));
        botonBorrarUltimo.setPreferredSize(new java.awt.Dimension(50, 50));
        botonBorrarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarUltimoActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonBorrarUltimo);

        botonPorcentaje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonPorcentaje.setText("%");
        botonPorcentaje.setToolTipText("");
        botonPorcentaje.setFocusable(false);
        botonPorcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPorcentaje.setMaximumSize(new java.awt.Dimension(50, 50));
        botonPorcentaje.setMinimumSize(new java.awt.Dimension(50, 50));
        botonPorcentaje.setPreferredSize(new java.awt.Dimension(50, 50));
        botonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPorcentajeActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonPorcentaje);

        botonSiete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonSiete.setText("7");
        botonSiete.setFocusable(false);
        botonSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSiete.setMaximumSize(new java.awt.Dimension(50, 50));
        botonSiete.setMinimumSize(new java.awt.Dimension(50, 50));
        botonSiete.setPreferredSize(new java.awt.Dimension(50, 50));
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonSiete);

        botonOcho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonOcho.setText("8");
        botonOcho.setFocusable(false);
        botonOcho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonOcho.setMaximumSize(new java.awt.Dimension(50, 50));
        botonOcho.setMinimumSize(new java.awt.Dimension(50, 50));
        botonOcho.setPreferredSize(new java.awt.Dimension(50, 50));
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonOcho);

        botonNueve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonNueve.setText("9");
        botonNueve.setFocusable(false);
        botonNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNueve.setMaximumSize(new java.awt.Dimension(50, 50));
        botonNueve.setMinimumSize(new java.awt.Dimension(50, 50));
        botonNueve.setPreferredSize(new java.awt.Dimension(50, 50));
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonNueve);

        botonDividir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonDividir.setText("/");
        botonDividir.setFocusable(false);
        botonDividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDividir.setMaximumSize(new java.awt.Dimension(50, 50));
        botonDividir.setMinimumSize(new java.awt.Dimension(50, 50));
        botonDividir.setPreferredSize(new java.awt.Dimension(50, 50));
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonDividir);

        botonCuatro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCuatro.setText("4");
        botonCuatro.setFocusable(false);
        botonCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCuatro.setMaximumSize(new java.awt.Dimension(50, 50));
        botonCuatro.setMinimumSize(new java.awt.Dimension(50, 50));
        botonCuatro.setPreferredSize(new java.awt.Dimension(50, 50));
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonCuatro);

        botonCinco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCinco.setText("5");
        botonCinco.setFocusable(false);
        botonCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCinco.setMaximumSize(new java.awt.Dimension(50, 50));
        botonCinco.setMinimumSize(new java.awt.Dimension(50, 50));
        botonCinco.setPreferredSize(new java.awt.Dimension(50, 50));
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonCinco);

        botonSeis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonSeis.setText("6");
        botonSeis.setFocusable(false);
        botonSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSeis.setMaximumSize(new java.awt.Dimension(50, 50));
        botonSeis.setMinimumSize(new java.awt.Dimension(50, 50));
        botonSeis.setPreferredSize(new java.awt.Dimension(50, 50));
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonSeis);

        botonMultiplicar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonMultiplicar.setText("*");
        botonMultiplicar.setFocusable(false);
        botonMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMultiplicar.setMaximumSize(new java.awt.Dimension(50, 50));
        botonMultiplicar.setMinimumSize(new java.awt.Dimension(50, 50));
        botonMultiplicar.setPreferredSize(new java.awt.Dimension(50, 50));
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonMultiplicar);

        botonUno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonUno.setText("1");
        botonUno.setFocusable(false);
        botonUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonUno.setMaximumSize(new java.awt.Dimension(50, 50));
        botonUno.setMinimumSize(new java.awt.Dimension(50, 50));
        botonUno.setPreferredSize(new java.awt.Dimension(50, 50));
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonUno);

        botonDos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonDos.setText("2");
        botonDos.setFocusable(false);
        botonDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDos.setMaximumSize(new java.awt.Dimension(50, 50));
        botonDos.setMinimumSize(new java.awt.Dimension(50, 50));
        botonDos.setPreferredSize(new java.awt.Dimension(50, 50));
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonDos);

        botonTres.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonTres.setText("3");
        botonTres.setFocusable(false);
        botonTres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTres.setMaximumSize(new java.awt.Dimension(50, 50));
        botonTres.setMinimumSize(new java.awt.Dimension(50, 50));
        botonTres.setPreferredSize(new java.awt.Dimension(50, 50));
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonTres);

        botonRestar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonRestar.setText("-");
        botonRestar.setFocusable(false);
        botonRestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRestar.setMaximumSize(new java.awt.Dimension(50, 50));
        botonRestar.setMinimumSize(new java.awt.Dimension(50, 50));
        botonRestar.setPreferredSize(new java.awt.Dimension(50, 50));
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonRestar);

        botonCero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCero.setText("0");
        botonCero.setFocusable(false);
        botonCero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCero.setMaximumSize(new java.awt.Dimension(50, 50));
        botonCero.setMinimumSize(new java.awt.Dimension(50, 50));
        botonCero.setPreferredSize(new java.awt.Dimension(50, 50));
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonCero);

        botonDecimal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonDecimal.setText(".");
        botonDecimal.setFocusable(false);
        botonDecimal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDecimal.setMaximumSize(new java.awt.Dimension(50, 50));
        botonDecimal.setMinimumSize(new java.awt.Dimension(50, 50));
        botonDecimal.setPreferredSize(new java.awt.Dimension(50, 50));
        botonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDecimalActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonDecimal);

        botonIgual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonIgual.setText("=");
        botonIgual.setFocusable(false);
        botonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIgual.setMaximumSize(new java.awt.Dimension(50, 50));
        botonIgual.setMinimumSize(new java.awt.Dimension(50, 50));
        botonIgual.setPreferredSize(new java.awt.Dimension(50, 50));
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonIgual);

        botonSumar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonSumar.setText("+");
        botonSumar.setFocusable(false);
        botonSumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSumar.setMaximumSize(new java.awt.Dimension(50, 100));
        botonSumar.setMinimumSize(new java.awt.Dimension(50, 100));
        botonSumar.setPreferredSize(new java.awt.Dimension(50, 100));
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        tecladoPanel.add(botonSumar);

        add(tecladoPanel, java.awt.BorderLayout.CENTER);

        displayPanel.setFocusable(false);
        displayPanel.setMaximumSize(new java.awt.Dimension(240, 60));
        displayPanel.setMinimumSize(new java.awt.Dimension(240, 60));
        displayPanel.setPreferredSize(new java.awt.Dimension(240, 60));
        displayPanel.setLayout(new java.awt.GridLayout(2, 1));

        textboxOutput.setEditable(false);
        textboxOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textboxOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textboxOutput.setFocusable(false);
        textboxOutput.setMaximumSize(new java.awt.Dimension(240, 30));
        textboxOutput.setMinimumSize(new java.awt.Dimension(240, 30));
        textboxOutput.setPreferredSize(new java.awt.Dimension(240, 30));
        textboxOutput.setRequestFocusEnabled(false);
        displayPanel.add(textboxOutput);

        textboxInput.setEditable(false);
        textboxInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textboxInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textboxInput.setText("0");
        textboxInput.setMaximumSize(new java.awt.Dimension(240, 30));
        textboxInput.setMinimumSize(new java.awt.Dimension(240, 30));
        textboxInput.setPreferredSize(new java.awt.Dimension(240, 30));
        textboxInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxInputActionPerformed(evt);
            }
        });
        textboxInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textboxInputKeyPressed(evt);
            }
        });
        displayPanel.add(textboxInput);

        add(displayPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    
    //evento oprimir el boton de sumar
    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        operar('+');
    }//GEN-LAST:event_botonSumarActionPerformed

    //evento oprimir el boton de restar
    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        operar('-');
    }//GEN-LAST:event_botonRestarActionPerformed

    //evento oprimir el boton de multiplicar
    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        operar('*');        
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    //evento oprimir el boton de dividir
    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        operar('/');
    }//GEN-LAST:event_botonDividirActionPerformed

    //evento oprimir el boton de porcentaje
    private void botonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPorcentajeActionPerformed
        porcentaje();
    }//GEN-LAST:event_botonPorcentajeActionPerformed

    //evento oprimir el boton igual
    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
       igualar();
    }//GEN-LAST:event_botonIgualActionPerformed

    //evento oprimir el boton cancelar
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        reiniciarValores();
    }//GEN-LAST:event_botonCancelarActionPerformed

    //evento oprimir el boton borrar
    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        reiniciarEntrada();
    }//GEN-LAST:event_botonBorrarActionPerformed

    //evento oprimir boton cero
    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
       ingresar("0");
    }//GEN-LAST:event_botonCeroActionPerformed
    
    //evento oprimir boton decimal
    private void botonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDecimalActionPerformed
        
        if(!this.decimal)
        {    
            ingresar(".");
            this.decimal=true;
        }
        
    }//GEN-LAST:event_botonDecimalActionPerformed

    ////evento oprimir boton uno
    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
       ingresar("1");
    }//GEN-LAST:event_botonUnoActionPerformed

    //evento oprimir boton dos
    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        ingresar("2");
    }//GEN-LAST:event_botonDosActionPerformed

    //evento oprimir boton tres
    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        ingresar("3");
    }//GEN-LAST:event_botonTresActionPerformed

    //evento oprimir boton cuatro
    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        ingresar("4");
    }//GEN-LAST:event_botonCuatroActionPerformed

    //evento oprimir boton cinco
    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
       ingresar("5");
    }//GEN-LAST:event_botonCincoActionPerformed

    //evento oprimir boton seis
    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        ingresar("6");
    }//GEN-LAST:event_botonSeisActionPerformed

    //evento oprimir boton siete
    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        ingresar("7");
    }//GEN-LAST:event_botonSieteActionPerformed

    //evento oprimir boton ocho
    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        ingresar("8");
    }//GEN-LAST:event_botonOchoActionPerformed

    //evento oprimir boton nueve
    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        ingresar("9");
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonBorrarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarUltimoActionPerformed
        borrarUltimo();
    }//GEN-LAST:event_botonBorrarUltimoActionPerformed

    private void textboxInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxInputActionPerformed
      botonIgualActionPerformed(evt);
    }//GEN-LAST:event_textboxInputActionPerformed

    private void textboxInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textboxInputKeyPressed
        
        
        switch(evt.getKeyChar())
        {
            case '%' : botonPorcentaje.doClick();break;
            
            case '7' : botonSiete.doClick();       break;
            case '8' : botonOcho.doClick();        break;
            case '9' : botonNueve.doClick();       break;
            case '/' : botonDividir.doClick();     break;
            
            case '4' : botonCuatro.doClick();      break;
            case '5' : botonCinco.doClick();       break;
            case '6' : botonSeis.doClick();        break;
            case '*' : botonMultiplicar.doClick(); break;
            
            case '1' : botonUno.doClick();         break;
            case '2' : botonDos.doClick();         break;
            case '3' : botonTres.doClick();        break;
            case '-' : botonRestar.doClick();      break;
            
            case '0' : botonCero.doClick();        break;
            case '.' : botonDecimal.doClick();     break;
            case ',' : botonDecimal.doClick();     break;
            case '=' : botonIgual.doClick();       break;
            case '+' : botonSumar.doClick();       break;
        }
        
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_BACK_SPACE: botonBorrarUltimo.doClick(); break;
            case KeyEvent.VK_ESCAPE:     botonCancelar.doClick();     break;
            case KeyEvent.VK_DELETE:     botonBorrar.doClick();       break;
        }
        
    }//GEN-LAST:event_textboxInputKeyPressed

    
    public static void main(String args[])
    {
	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {}
        
        
        JFrame ventana=new JFrame("Calculadora");
        CalculadoraGuiPanel calculadora=new CalculadoraGuiPanel();
        calculadora.setLocation(0,0);
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.setMinimumSize(new Dimension(230, 345));
        ventana.setResizable(false);
        ventana.setVisible(true);
        ventana.add(calculadora);
        calculadora.textboxInput.requestFocusInWindow();
    }
    
    
    private void reiniciarValores()
    {
        this.total=new BigDecimal("0").setScale(ESCALA);
        this.igual=false;
        this.output=" ";
        this.textboxOutput.setText("");
        reiniciarEntrada();   
    }
    
    private void reiniciarEntrada()
    {
        this.textboxInput.setText("0");
        this.textboxInput.setEditable(false);
        this.decimal=false;
        this.input=" ";
    }
    
    //controla el ingreso mediante los botones
    private void ingresar(String dato)
    {
        if(this.igual)
        {
            this.igual=false;
            reiniciarEntrada();
        }
        if(this.textboxInput.getText().equals("0") && !dato.equals(".") )
            this.textboxInput.setText(dato);
        else
           this.textboxInput.setText(this.textboxInput.getText()+dato);
             
    }
    
    private void porcentaje()
    {
        //valida que el campo de entrada no este vacio
        if(!this.textboxInput.getText().isEmpty() )
        {   
            this.input=this.textboxInput.getText();
            //valida que se pueda hacer el parseo
            if(canItParseToBigDecimal())
            {
                try
                {
                    BigDecimal a=new BigDecimal(this.input);
                    if(!output.equals(" "))
                       a=this.total.multiply(new BigDecimal(this.input));
                        
                    a=a.divide(new BigDecimal("100.0000"),ESCALA+1,TIPO_DE_REDONDEO);   
                    this.textboxInput.setText(a.stripTrailingZeros().toPlainString());
                    operar('%');
                    igualar();
                    
                }
                catch(ArithmeticException e)
                {
                    reiniciarValores();
                    imprimirError();
                }
            }
        }
    }
    
    private void igualar()
    {
        //si se ha ingresado al menos un número
       if(!this.output.equals(" "))
       {
           operar('=');
           BigDecimal tb=this.total.setScale(ESCALA, TIPO_DE_REDONDEO);
           reiniciarValores();
           this.igual=true;
           this.decimal=true;
           this.textboxInput.setText(tb.stripTrailingZeros().toPlainString());
           
       }
    }

   //valida y ejecuta las operaciones
    private void operar(Character nuevoOperador)
    {
        //valida que el campo de entrada no este vacio
        if(!this.textboxInput.getText().isEmpty() )
        {   
            this.input=this.textboxInput.getText();
            
            //valida que se pueda hacer el parseo
            if(canItParseToBigDecimal())
            {
                boolean isMostrar=true;
               //si se cumple es por que este es el primer número
               if(output.equals(" "))
                {
                    this.output=this.input+nuevoOperador;
                    this.total=stringToBigDecimal();
		} 
               else
               {
                    //busca el último operador en la cola
                    Character ultimoOperador=this.output.charAt(this.output.length()-1);
                    
                    try
                    {
                        ejecutarOperacion(ultimoOperador);
                        this.output+=this.input+nuevoOperador;
                        
                    }
                    catch(ArithmeticException e)
                    {
                        reiniciarValores();
                        imprimirError();
                        isMostrar=false;
                    }      
         	} 
                
               if(isMostrar)
               {
                   reiniciarEntrada();
                   this.textboxOutput.setText(this.output);
               }
               
            } //fin de if(pasarADoubleBoolean())
        
        }//fin de if(!this.textboxInput.getText().isEmpty() )
    
    }//fin de private void operar(char nuevoOperador)
    
    
    private void ejecutarOperacion(Character ultimoOperador) throws ArithmeticException
    {
        switch(ultimoOperador)
        {
            case '+': this.total=this.total.add(stringToBigDecimal());                               break;
            case '-': this.total=this.total.subtract(stringToBigDecimal());                          break;
            case '*': this.total=this.total.multiply(stringToBigDecimal());                          break;
            case '/': this.total=this.total.divide(stringToBigDecimal(),ESCALA+1,TIPO_DE_REDONDEO);  break;
        }
        
    }
    
    private void borrarUltimo()
    {  
        if(this.textboxInput.getText().isEmpty() || this.igual)
            reiniciarEntrada();
        else
        {
            Character ultimo=this.textboxInput.getText().charAt(this.textboxInput.getText().length()-1);
            if(ultimo.equals('.'))
                this.decimal=false;
            
            this.textboxInput.setText(this.textboxInput.getText().substring(0, this.textboxInput.getText().length()-1));
            
            if(this.textboxInput.getText().isEmpty())
                reiniciarEntrada();
        }
    }
    
    //valida que se pueda hacer el parseo, y controla la execepcion NumberFormatException
    private boolean canItParseToBigDecimal()
    {
        try
        { 
            new BigDecimal(this.input);
            return true;
        }
        catch(NumberFormatException formatoE)
        {
            reiniciarValores();
            imprimirError();
            return false;
        }
    }
    
    //retorna lo ingresado en BigDecimal
    private BigDecimal stringToBigDecimal()
    {
        return new BigDecimal(this.input);
    }
    
    private void imprimirError()
    {
        this.textboxOutput.setText("Ha ocurrido un error de operación");
        this.textboxInput.setText ("Precione C");
        this.textboxInput.setEditable(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarUltimo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDecimal;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonPorcentaje;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonSumar;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel tecladoPanel;
    private javax.swing.JTextField textboxInput;
    private javax.swing.JTextField textboxOutput;
    // End of variables declaration//GEN-END:variables

}//public class CalculadoraGuiPanel extends javax.swing.JPanel
