
package calculadora;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JFrame;
import javax.swing.UIManager;

public class CalculadoraGuiPanel extends javax.swing.JPanel 
{
    private String input;
    private String output;
    private boolean igual,decimal;
    private BigDecimal total;
    private final static RoundingMode TIPO_DE_REDONDEO=RoundingMode.HALF_EVEN;
    private final static int ESCALA=20;
    
    public CalculadoraGuiPanel() 
    {
        initComponents();
        reiniciarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tecladoPanel = new javax.swing.JPanel();
        cancelarBoton = new javax.swing.JButton();
        borrarBoton = new javax.swing.JButton();
        borrarUltimoBoton = new javax.swing.JButton();
        porcentajeBoton = new javax.swing.JButton();
        sieteBoton = new javax.swing.JButton();
        ochoBoton = new javax.swing.JButton();
        nueveBoton = new javax.swing.JButton();
        dividirBoton = new javax.swing.JButton();
        cuatroBoton = new javax.swing.JButton();
        cincoBoton = new javax.swing.JButton();
        seisBoton = new javax.swing.JButton();
        multiplicarBoton = new javax.swing.JButton();
        unoBoton = new javax.swing.JButton();
        dosBoton = new javax.swing.JButton();
        tresBoton = new javax.swing.JButton();
        restarBoton = new javax.swing.JButton();
        ceroBoton = new javax.swing.JButton();
        puntoDecimalBoton = new javax.swing.JButton();
        igualBoton = new javax.swing.JButton();
        sumarBoton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        textboxOutput = new javax.swing.JTextField();
        textboxInput = new javax.swing.JTextField();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(240, 310));
        setMinimumSize(new java.awt.Dimension(240, 310));
        setPreferredSize(new java.awt.Dimension(240, 310));
        setLayout(new java.awt.BorderLayout());

        tecladoPanel.setFocusable(false);
        tecladoPanel.setMaximumSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setMinimumSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setPreferredSize(new java.awt.Dimension(200, 250));
        tecladoPanel.setLayout(new java.awt.GridLayout(5, 4));

        cancelarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelarBoton.setText("C");
        cancelarBoton.setFocusable(false);
        cancelarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cancelarBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cancelarBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(cancelarBoton);

        borrarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        borrarBoton.setText("CE");
        borrarBoton.setFocusable(false);
        borrarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrarBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        borrarBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        borrarBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(borrarBoton);

        borrarUltimoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        borrarUltimoBoton.setText("<-");
        borrarUltimoBoton.setFocusable(false);
        borrarUltimoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrarUltimoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        borrarUltimoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        borrarUltimoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        borrarUltimoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUltimoBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(borrarUltimoBoton);

        porcentajeBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        porcentajeBoton.setText("%");
        porcentajeBoton.setToolTipText("");
        porcentajeBoton.setFocusable(false);
        porcentajeBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        porcentajeBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        porcentajeBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        porcentajeBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        porcentajeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(porcentajeBoton);

        sieteBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sieteBoton.setText("7");
        sieteBoton.setFocusable(false);
        sieteBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sieteBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        sieteBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        sieteBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        sieteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(sieteBoton);

        ochoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ochoBoton.setText("8");
        ochoBoton.setFocusable(false);
        ochoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ochoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        ochoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        ochoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        ochoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(ochoBoton);

        nueveBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nueveBoton.setText("9");
        nueveBoton.setFocusable(false);
        nueveBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nueveBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        nueveBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        nueveBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        nueveBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(nueveBoton);

        dividirBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dividirBoton.setText("/");
        dividirBoton.setFocusable(false);
        dividirBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dividirBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        dividirBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        dividirBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        dividirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(dividirBoton);

        cuatroBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cuatroBoton.setText("4");
        cuatroBoton.setFocusable(false);
        cuatroBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuatroBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cuatroBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cuatroBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        cuatroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(cuatroBoton);

        cincoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cincoBoton.setText("5");
        cincoBoton.setFocusable(false);
        cincoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cincoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        cincoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        cincoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        cincoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(cincoBoton);

        seisBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seisBoton.setText("6");
        seisBoton.setFocusable(false);
        seisBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seisBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        seisBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        seisBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        seisBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(seisBoton);

        multiplicarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        multiplicarBoton.setText("*");
        multiplicarBoton.setFocusable(false);
        multiplicarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiplicarBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        multiplicarBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        multiplicarBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplicarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(multiplicarBoton);

        unoBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        unoBoton.setText("1");
        unoBoton.setFocusable(false);
        unoBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        unoBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        unoBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        unoBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        unoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(unoBoton);

        dosBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dosBoton.setText("2");
        dosBoton.setFocusable(false);
        dosBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dosBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        dosBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        dosBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        dosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(dosBoton);

        tresBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tresBoton.setText("3");
        tresBoton.setFocusable(false);
        tresBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tresBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        tresBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        tresBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        tresBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(tresBoton);

        restarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        restarBoton.setText("-");
        restarBoton.setFocusable(false);
        restarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restarBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        restarBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        restarBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        restarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(restarBoton);

        ceroBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ceroBoton.setText("0");
        ceroBoton.setFocusable(false);
        ceroBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ceroBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        ceroBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        ceroBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        ceroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(ceroBoton);

        puntoDecimalBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        puntoDecimalBoton.setText(".");
        puntoDecimalBoton.setFocusable(false);
        puntoDecimalBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        puntoDecimalBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        puntoDecimalBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        puntoDecimalBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        puntoDecimalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoDecimalBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(puntoDecimalBoton);

        igualBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        igualBoton.setText("=");
        igualBoton.setFocusable(false);
        igualBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        igualBoton.setMaximumSize(new java.awt.Dimension(50, 50));
        igualBoton.setMinimumSize(new java.awt.Dimension(50, 50));
        igualBoton.setPreferredSize(new java.awt.Dimension(50, 50));
        igualBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(igualBoton);

        sumarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sumarBoton.setText("+");
        sumarBoton.setFocusable(false);
        sumarBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sumarBoton.setMaximumSize(new java.awt.Dimension(50, 100));
        sumarBoton.setMinimumSize(new java.awt.Dimension(50, 100));
        sumarBoton.setPreferredSize(new java.awt.Dimension(50, 100));
        sumarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarBotonActionPerformed(evt);
            }
        });
        tecladoPanel.add(sumarBoton);

        add(tecladoPanel, java.awt.BorderLayout.CENTER);

        displayPanel.setFocusable(false);
        displayPanel.setMaximumSize(new java.awt.Dimension(240, 60));
        displayPanel.setMinimumSize(new java.awt.Dimension(240, 60));
        displayPanel.setPreferredSize(new java.awt.Dimension(240, 60));
        displayPanel.setLayout(new java.awt.GridLayout(2, 1));

        textboxOutput.setEditable(false);
        textboxOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textboxOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textboxOutput.setFocusable(false);
        textboxOutput.setMaximumSize(new java.awt.Dimension(240, 30));
        textboxOutput.setMinimumSize(new java.awt.Dimension(240, 30));
        textboxOutput.setPreferredSize(new java.awt.Dimension(240, 30));
        textboxOutput.setRequestFocusEnabled(false);
        displayPanel.add(textboxOutput);

        textboxInput.setEditable(false);
        textboxInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textboxInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textboxInput.setText("0");
        textboxInput.setMaximumSize(new java.awt.Dimension(240, 30));
        textboxInput.setMinimumSize(new java.awt.Dimension(240, 30));
        textboxInput.setPreferredSize(new java.awt.Dimension(240, 30));
        textboxInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxInputActionPerformed(evt);
            }
        });
        textboxInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textboxInputKeyPressed(evt);
            }
        });
        displayPanel.add(textboxInput);

        add(displayPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    
    //evento oprimir el boton de sumar
    private void sumarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarBotonActionPerformed
        operar('+');
    }//GEN-LAST:event_sumarBotonActionPerformed

    //evento oprimir el boton de restar
    private void restarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarBotonActionPerformed
        operar('-');
    }//GEN-LAST:event_restarBotonActionPerformed

    //evento oprimir el boton de multiplicar
    private void multiplicarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarBotonActionPerformed
        operar('*');        
    }//GEN-LAST:event_multiplicarBotonActionPerformed

    //evento oprimir el boton de dividir
    private void dividirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirBotonActionPerformed
        operar('/');
    }//GEN-LAST:event_dividirBotonActionPerformed

    //evento oprimir el boton de porcentaje
    private void porcentajeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeBotonActionPerformed
        porcentaje();
    }//GEN-LAST:event_porcentajeBotonActionPerformed

    //evento oprimir el boton igual
    private void igualBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBotonActionPerformed
       igualar();
    }//GEN-LAST:event_igualBotonActionPerformed

    //evento oprimir el boton cancelar
    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        reiniciarValores();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    //evento oprimir el boton borrar
    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
        reiniciarEntrada();
    }//GEN-LAST:event_borrarBotonActionPerformed

    //evento oprimir boton cero
    private void ceroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBotonActionPerformed
       ingresar("0");
    }//GEN-LAST:event_ceroBotonActionPerformed
    
    //evento oprimir boton decimal
    private void puntoDecimalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoDecimalBotonActionPerformed
        
        if(!this.decimal)
        {    
            ingresar(".");
            this.decimal=true;
        }
        
    }//GEN-LAST:event_puntoDecimalBotonActionPerformed

    ////evento oprimir boton uno
    private void unoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBotonActionPerformed
       ingresar("1");
    }//GEN-LAST:event_unoBotonActionPerformed

    //evento oprimir boton dos
    private void dosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBotonActionPerformed
        ingresar("2");
    }//GEN-LAST:event_dosBotonActionPerformed

    //evento oprimir boton tres
    private void tresBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBotonActionPerformed
        ingresar("3");
    }//GEN-LAST:event_tresBotonActionPerformed

    //evento oprimir boton cuatro
    private void cuatroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBotonActionPerformed
        ingresar("4");
    }//GEN-LAST:event_cuatroBotonActionPerformed

    //evento oprimir boton cinco
    private void cincoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBotonActionPerformed
       ingresar("5");
    }//GEN-LAST:event_cincoBotonActionPerformed

    //evento oprimir boton seis
    private void seisBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBotonActionPerformed
        ingresar("6");
    }//GEN-LAST:event_seisBotonActionPerformed

    //evento oprimir boton siete
    private void sieteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBotonActionPerformed
        ingresar("7");
    }//GEN-LAST:event_sieteBotonActionPerformed

    //evento oprimir boton ocho
    private void ochoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBotonActionPerformed
        ingresar("8");
    }//GEN-LAST:event_ochoBotonActionPerformed

    //evento oprimir boton nueve
    private void nueveBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBotonActionPerformed
        ingresar("9");
    }//GEN-LAST:event_nueveBotonActionPerformed

    private void borrarUltimoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUltimoBotonActionPerformed
        borrarUltimo();
    }//GEN-LAST:event_borrarUltimoBotonActionPerformed

    private void textboxInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxInputActionPerformed
      igualBoton.doClick();
    }//GEN-LAST:event_textboxInputActionPerformed

    private void textboxInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textboxInputKeyPressed
        
        
        switch(evt.getKeyChar())
        {
            case '%' : porcentajeBoton.doClick();break;
            
            case '7' : sieteBoton.doClick();       break;
            case '8' : ochoBoton.doClick();        break;
            case '9' : nueveBoton.doClick();       break;
            case '/' : dividirBoton.doClick();     break;
            
            case '4' : cuatroBoton.doClick();      break;
            case '5' : cincoBoton.doClick();       break;
            case '6' : seisBoton.doClick();        break;
            case '*' : multiplicarBoton.doClick(); break;
            
            case '1' : unoBoton.doClick();         break;
            case '2' : dosBoton.doClick();         break;
            case '3' : tresBoton.doClick();        break;
            case '-' : restarBoton.doClick();      break;
            
            case '0' : ceroBoton.doClick();        break;
            case '.' : puntoDecimalBoton.doClick();     break;
            case ',' : puntoDecimalBoton.doClick();     break;
            case '=' : igualBoton.doClick();       break;
            case '+' : sumarBoton.doClick();       break;
        }
        
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_BACK_SPACE: borrarUltimoBoton.doClick(); break;
            case KeyEvent.VK_ESCAPE:     cancelarBoton.doClick();     break;
            case KeyEvent.VK_DELETE:     borrarBoton.doClick();       break;
        }
        
    }//GEN-LAST:event_textboxInputKeyPressed

    
    public static void main(String args[])
    {
	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {}
        
        
        JFrame ventana=new JFrame("Calculadora");
        CalculadoraGuiPanel calculadora=new CalculadoraGuiPanel();
        calculadora.setLocation(0,0);
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.setMinimumSize(new Dimension(230, 345));
        ventana.setResizable(false);
        ventana.setVisible(true);
        ventana.add(calculadora);
        calculadora.textboxInput.requestFocusInWindow();
    }
    
    
    private void reiniciarValores()
    {
        this.total=new BigDecimal("0").setScale(ESCALA);
        this.igual=false;
        this.output=" ";
        this.textboxOutput.setText("");
        reiniciarEntrada();   
    }
    
    private void reiniciarEntrada()
    {
        this.textboxInput.setText("0");
        this.textboxInput.setEditable(false);
        this.decimal=false;
        this.input=" ";
    }
    
    //controla el ingreso mediante los botones
    private void ingresar(String dato)
    {
        if(this.igual)
        {
            this.igual=false;
            reiniciarEntrada();
        }
        if(this.textboxInput.getText().equals("0") && !dato.equals(".") )
            this.textboxInput.setText(dato);
        else
           this.textboxInput.setText(this.textboxInput.getText()+dato);
             
    }
    
    private void porcentaje()
    {
        //valida que el campo de entrada no este vacio
        if(!this.textboxInput.getText().isEmpty() )
        {   
            this.input=this.textboxInput.getText();
            //valida que se pueda hacer el parseo
            if(canItParseToBigDecimal())
            {
                try
                {
                    BigDecimal a=new BigDecimal(this.input);
                    if(!output.equals(" "))
                       a=this.total.multiply(new BigDecimal(this.input));
                        
                    a=a.divide(new BigDecimal("100.0000"),ESCALA+1,TIPO_DE_REDONDEO);   
                    this.textboxInput.setText(a.stripTrailingZeros().toPlainString());
                    operar('%');
                    igualar();
                    
                }
                catch(ArithmeticException e)
                {
                    reiniciarValores();
                    imprimirError();
                }
            }
        }
    }
    
    private void igualar()
    {
        //si se ha ingresado al menos un número
       if(!this.output.equals(" "))
       {
           operar('=');
           BigDecimal tb=this.total.setScale(ESCALA, TIPO_DE_REDONDEO);
           reiniciarValores();
           this.igual=true;
           this.decimal=true;
           this.textboxInput.setText(tb.stripTrailingZeros().toPlainString());
           
       }
    }

   //valida y ejecuta las operaciones
    private void operar(Character nuevoOperador)
    {
        //valida que el campo de entrada no este vacio
        if(!this.textboxInput.getText().isEmpty() )
        {   
            this.input=this.textboxInput.getText();
            
            //valida que se pueda hacer el parseo
            if(canItParseToBigDecimal())
            {
                boolean isMostrar=true;
               //si se cumple es por que este es el primer número
               if(output.equals(" "))
                {
                    this.output=this.input+nuevoOperador;
                    this.total=stringToBigDecimal();
		} 
               else
               {
                    //busca el último operador en la cola
                    Character ultimoOperador=this.output.charAt(this.output.length()-1);
                    
                    try
                    {
                        ejecutarOperacion(ultimoOperador);
                        this.output+=this.input+nuevoOperador;
                        
                    }
                    catch(ArithmeticException e)
                    {
                        reiniciarValores();
                        imprimirError();
                        isMostrar=false;
                    }      
         	} 
                
               if(isMostrar)
               {
                   reiniciarEntrada();
                   this.textboxOutput.setText(this.output);
               }
               
            } //fin de if(pasarADoubleBoolean())
        
        }//fin de if(!this.textboxInput.getText().isEmpty() )
    
    }//fin de private void operar(char nuevoOperador)
    
    
    private void ejecutarOperacion(Character ultimoOperador) throws ArithmeticException
    {
        switch(ultimoOperador)
        {
            case '+': this.total=this.total.add(stringToBigDecimal());                               break;
            case '-': this.total=this.total.subtract(stringToBigDecimal());                          break;
            case '*': this.total=this.total.multiply(stringToBigDecimal());                          break;
            case '/': this.total=this.total.divide(stringToBigDecimal(),ESCALA+1,TIPO_DE_REDONDEO);  break;
        }
        
    }
    
    private void borrarUltimo()
    {  
        if(this.textboxInput.getText().isEmpty() || this.igual)
            reiniciarEntrada();
        else
        {
            Character ultimo=this.textboxInput.getText().charAt(this.textboxInput.getText().length()-1);
            if(ultimo.equals('.'))
                this.decimal=false;
            
            this.textboxInput.setText(this.textboxInput.getText().substring(0, this.textboxInput.getText().length()-1));
            
            if(this.textboxInput.getText().isEmpty())
                reiniciarEntrada();
        }
    }
    
    //valida que se pueda hacer el parseo, y controla la execepcion NumberFormatException
    private boolean canItParseToBigDecimal()
    {
        try
        { 
            new BigDecimal(this.input);
            return true;
        }
        catch(NumberFormatException formatoE)
        {
            reiniciarValores();
            imprimirError();
            return false;
        }
    }
    
    //retorna lo ingresado en BigDecimal
    private BigDecimal stringToBigDecimal()
    {
        return new BigDecimal(this.input);
    }
    
    private void imprimirError()
    {
        this.textboxOutput.setText("Ha ocurrido un error de operación");
        this.textboxInput.setText ("Precione C");
        this.textboxInput.setEditable(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JButton borrarUltimoBoton;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JButton ceroBoton;
    private javax.swing.JButton cincoBoton;
    private javax.swing.JButton cuatroBoton;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton dividirBoton;
    private javax.swing.JButton dosBoton;
    private javax.swing.JButton igualBoton;
    private javax.swing.JButton multiplicarBoton;
    private javax.swing.JButton nueveBoton;
    private javax.swing.JButton ochoBoton;
    private javax.swing.JButton porcentajeBoton;
    private javax.swing.JButton puntoDecimalBoton;
    private javax.swing.JButton restarBoton;
    private javax.swing.JButton seisBoton;
    private javax.swing.JButton sieteBoton;
    private javax.swing.JButton sumarBoton;
    private javax.swing.JPanel tecladoPanel;
    private javax.swing.JTextField textboxInput;
    private javax.swing.JTextField textboxOutput;
    private javax.swing.JButton tresBoton;
    private javax.swing.JButton unoBoton;
    // End of variables declaration//GEN-END:variables

}//public class CalculadoraGuiPanel extends javax.swing.JPanel
